<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;
use yii\validators\ImageValidator;
/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property string $pro_name
 * @property string $pro_img
 */
class Uploadfile extends \yii\db\ActiveRecord
{
    public function beforeValidate()
    {
        $this->image = UploadedFile::getInstance($this, 'image');
        return parent::beforeValidate(); // TODO: Change the autogenerated stub

    }

    public function afterValidate()
    {
        if ($this->image) {
            $this->image->saveAs(Yii::$app->basePath . '/web/upload/' . $this->image);
        }
        parent::afterValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'uploadfile';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['name'], 'string', 'max' => 32],
            ['image', 'file',
                'extensions' => 'png, jpg',
                'skipOnEmpty' => false
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'name',
            'image' => 'image',
        ];
    }
}
